### ISSUE TITLE
bad decrypt error on decrypting Assertion via libsaml

### ISSUE THREAD

**Issue by sahild** [digidentity/xmlenc#19]
I am having a hard time to decrypt this assertion via libsaml:
https://gist.github.com/sahild/752f5a446bb16371f014

This error is being raised:
bad decrypt
/home/sahild/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/xmlenc-0.1.6/lib/xmlenc/algorithms/aes_cbc.rb:25:in `final'
/home/sahild/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/xmlenc-0.1.6/lib/xmlenc/algorithms/aes_cbc.rb:25:in `decrypt'
/home/sahild/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/xmlenc-0.1.6/lib/xmlenc/encrypted_data.rb:38:in `decrypt'
/home/sahild/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/xmlenc-0.1.6/lib/xmlenc/encrypted_document.rb:21:in `block in decrypt'
/home/sahild/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/xmlenc-0.1.6/lib/xmlenc/encrypted_document.rb:18:in `each'
/home/sahild/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/xmlenc-0.1.6/lib/xmlenc/encrypted_document.rb:18:in `decrypt'
/home/sahild/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/libsaml-2.5.2/lib/saml/util.rb:73:in `decrypt_assertion'

I have changed algorithms and everything. Was going through the source code and looking at the code seems that it fails at very early stage, not sure what i am missing.
Regards
Sahil

**Comment by benoist** [comment]
It could mean that the encryption key is incorrect. The encrypted key is decrypted with a private key, but this does not fail if it's an incorrect key, it just returns a different value. The cipher will fail, because the secret is incorrect.

**Comment by sahild** [comment]
thanks @benoist . On the basis of your hint , i am trying to gather further information. I am working on this leads now:
(1) the client issuing the encrypted assertions is a .net system and using this system https://www.componentsource.com/product/componentspace-saml2-component to encrypt their assertions. So may some weird .net to ruby issue
(2) I verified those saml responses on this online tool and it seemed to be able to decrypt them fine.
![saml_tool](https://cloud.githubusercontent.com/assets/354781/12188301/f49ed3f4-b5d9-11e5-8773-a7bc16d845c8.png)
.

**Comment by sahild** [comment]
Looks like data_key in the below steps is some garbage value:
     encrypted_document      = Xmlenc::EncryptedDocument.new(request_or_response.encrypted_assertion.to_xml)
     encrypted_document.decrypt(request_or_response.provider.private_key)
     encrypted_document.encrypted_keys.each do |encrypted_key|
       encrypted_data = encrypted_key.encrypted_data
       data_key       = encrypted_key.decrypt(request_or_response.provider.private_key)
       #below line fails
       encrypted_data.decrypt(data_key)
       end

**Comment by benoist** [comment]
It could well be the key. It's good practice to use random bytes to generate the symmetric key, but when you output them it's a bunch of weird characters.

But by the looks of it, you might be using the wrong private key as you're referring to the request_response provider. But you need the private key of your own provider to decryt.

**Comment by sahild** [comment]
@benoist  . thanks i debugged from that angle also but still no luck. i also hard-hoded the private key, but still same thing.

**Comment by benoist** [comment]
Do you have a failing example with test keys that you can send me?

**Comment by sahild** [comment]
thanks @benoist mailed you privately.
Appreciate your help!

**Comment by sahild** [comment]
Hi,
If anyone also facing this issue just update to the latest version of the gem.
I am using old version 
libsaml-2.5.2
xmlenc-0.1.6
due to which i was facing these issues.
Thank you @benoist for pointing that. Everything  is working great after the update.
